//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicHub.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public Nullable<int> Author { get; set; }
    
        public virtual Author Author1 { get; set; }
    }
}
